<a href="https://colab.research.google.com/github/mushrifa26/python-class-files/blob/main/day10numpy/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
list1=[1,4,8,7,5,2]

print(list1)
type(list1)


arr1=np.array(list1)
print(arr1)
type(arr1)
arr1.shape
arr1.size

[1, 4, 8, 7, 5, 2]
[1 4 8 7 5 2]


6

In [ ]:
import numpy as np

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
#arr2.shape
arr2.size

[[1 2 3]
 [4 5 6]]


6

In [ ]:
arr3=np.array([
    [
      [1,2,3],
      [4,5,6]
    ],
    [
        [6,7,8],
        [8,9,0]

    ]


])
print(arr3.shape)
print(arr3)
arr3.size


(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [8 9 0]]]


12

In [ ]:

import numpy as np
np.zeros(5)
np.zeros((3,4))
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
#array created with ones
import numpy as np
np.ones(5)

np.ones((3,4,5))
#np.ones((5,6))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
#identity matrix
np.identity(3)
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#arange()
arr6=np.arange(5)#by defualt
print(arr6)


[0 1 2 3 4]


In [ ]:
#custom
arr7=np.arange(4,15,2)
print(arr7)

[ 4  6  8 10 12 14]


In [ ]:
#floating point numbers
arr8=np.arange(0,1,0.2)
print(arr8)

[0.  0.2 0.4 0.6 0.8]


In [ ]:
#2D arrage
arr9=np.arange(12).reshape(3,4)

print(arr9)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#custom 2 d arange
arr10=np.arange(25,50,3).reshape(3,3)
print(arr10)

[[25 28 31]
 [34 37 40]
 [43 46 49]]


In [ ]:
#3d arange
arr11=np.arange(24).reshape(2,3,4)
print(arr11)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#dtype-datatype
arr_int=np.array([1,2,3],dtype=int)
print(arr_int)

[1 2 3]


In [ ]:
arr_float=np.array([1,2,3],dtype=float)
print(arr_float)

[1. 2. 3.]


In [ ]:
#numpy array properties and attributes
#1 ndim
#number of dimension
import numpy as np
arr2=np.array([[1,2,3],[1,3,4]])
print(arr2.ndim)
arr3=np.array([[[1,2,3],[4,5,6],[7,7,9]]])
print(arr3.ndim)
#print(arr2.ndim)
#print(arr3.ndim)
#2 shape
#print(arr1.shape)
#print(arr2.shape)
#print(arr3.shape)

2
3


In [ ]:
#size
#total number of elements in the arrays
print(arr1.size)
print(arr2.size)
print(arr3.size)


6
6
12


In [ ]:
#dtype
print(arr2.dtype)
print(arr_float.dtype)

int64
float64


In [ ]:
#itemsizeumber of bytes used to store one element in numpy
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1.itemsize)
#print(arr2.itemsize)
#print(arr_float.itemsize)

8


In [ ]:
#indexing and slicing
import numpy as np
arr1=np.array([1,3,6,8,9])

print(arr1)
print(arr1[0])
print(arr1[-1])
print(arr1[1])
print(arr2)
print(arr2[0,2])
print(arr2[1,2])

[1 3 6 8 9]
1
9
3
[[1 2 3]
 [1 3 4]]
3
4


In [ ]:
#slicing
print(arr1)
print(arr1[1:4])

[1 4 8 7 5 2]
[4 8 7]


In [ ]:
#2d slicin g

print(arr2)
print(arr2[])

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0:2,1:3])


[[2 3]
 [5 6]]


In [ ]:
#iteration
for x in arr1:
  print(x)

1
4
8
7
5
2


In [ ]:
for x in arr2:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#nditerm
for x in np.nditer(arr2):
  print(x)

1
2
3
4
5
6


In [ ]:
#arithmetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]


In [ ]:
#comparison operator
print(a<b)
print(a>b)
print(a==b)

[ True  True  True]
[False False False]
[False False False]


In [ ]:
#flatten
print(arr2)
flat_arr2=arr2.flatten()
print(flat_arr2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#random.randint
arr20=np.random.randint(10,50,size=10)
print(arr20)

[15 27 23 44 48 16 30 22 11 18]
